### ISSUE TITLE
unexpected results in the Arctic, considering gbif

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#1]
http://gimmefreshdata.github.io/#height=44&lat=73.02259157147301&limit=20&lng=-100.546875&taxonSelector=Aves%2CMammalia&traitSelector=&width=252&wktString=ENVELOPE%28170.859375%2C-11.953125%2C76.9999351181161%2C67.87554134672945%29&zoom=1

retrieved no results. 

I compared with http://www.gbif.org/occurrence/search?TAXON_KEY=359&TAXON_KEY=212&HAS_GEOSPATIAL_ISSUE=false&GEOMETRY=-119.53125+76.999935%2C-119.53125+69.657086%2C-79.453125+69.657086%2C-79.453125+76.999935%2C-119.53125+76.999935

What did I do wrong?

**Comment by jhpoelen** [comment]
Interesting! 

I clicked on http://gimmefreshdata.github.io/#height=44&lat=73.02259157147301&limit=20&lng=-100.546875&taxonSelector=Aves%2CMammalia&traitSelector=&width=252&wktString=ENVELOPE%28170.859375%2C-11.953125%2C76.9999351181161%2C67.87554134672945%29&zoom=1 and did find results (see screenshot below).

Did you try to refresh your browser or use a different browser? Perhaps previous results/versions were cached.

![screen shot 2016-03-15 at 10 39 36 am](https://cloud.githubusercontent.com/assets/1084872/13787714/42ff6b36-ea9a-11e5-8725-4e0b96a7d686.png)

**Comment by jhammock** [comment]
not reproducible; I'll holler if I ever see it again. Sorry!

**Comment by jhpoelen** [comment]
ok. please re-open issue when you see this again.
