### ISSUE TITLE
add ability to filter by data source

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/freshdata#10]
as suggested by Andrea Wiggins

**Comment by jhpoelen** [comment]
@jhammock would you imagine to this be used for the diff sub-selection or for the main search selectors (e.g. taxon, geospatial)?

**Comment by jhammock** [comment]
Main selectors- some people may have trust issues with some providers, and others may want to monitor only their home platform, and not have native capability to do so

**Comment by jhpoelen** [comment]
implemented as suggested.

**Comment by jhammock** [comment]
Hmm... I think this is not working, though I'm pretty sure I either performed or saw a positive test earlier. See results for 

http://api.effechecka.org/occurrences?limit=2&taxonSelector=Aves,Insecta&traitSelector=&wktString=POLYGON%20((-72.147216796875%20041.492120839687786,%20-72.147216796875%2043.11702412135048,%20-69.949951171875%2043.11702412135048,%20-69.949951171875%2041.492120839687786,%20-72.147216796875%2041.492120839687786))&source=gbif

**Comment by jhpoelen** [comment]
@jhammock did you create the api url yourself? Perhaps it is a documentation issue. When selecting a source, the source "query" is smashed in the traitSelector. This is the search page I created using the web widgets: http://gimmefreshdata.github.io/?limit=20&taxonSelector=Aves%2CInsecta&traitSelector=source%20%3D%3D%20gbif%20string&wktString=POLYGON%20%28%28-72.147216796875%2041.492120839687786%2C%20-72.147216796875%2043.11702412135048%2C%20-69.949951171875%2043.11702412135048%2C%20-69.949951171875%2041.492120839687786%2C%20-72.147216796875%2041.492120839687786%29%29

This page issues the following api request:

http://api.effechecka.org/occurrences?limit=20&taxonSelector=Aves%2CInsecta&traitSelector=source%20%3D%3D%20gbif%20string&wktString=POLYGON%20((-72.147216796875%2041.492120839687786%2C%20-72.147216796875%2043.11702412135048%2C%20-69.949951171875%2043.11702412135048%2C%20-69.949951171875%2041.492120839687786%2C%20-72.147216796875%2041.492120839687786))

Perhaps too lazy of me to cram the source selector into the trait selector?

**Comment by jhpoelen** [comment]
added documentation to https://github.com/gimmefreshdata/freshdata/wiki/api related to traitSelector

**Comment by jhpoelen** [comment]
@jhammock please re-open / comment if this issue persists or re-occurs
