### ISSUE TITLE
select tool insists on using- or at least displaying- the default Boston box

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#18]
I'm pretty sure this is a problem I did not encounter previously. Creating a search in Fresh Data now, if I delete the default search area around Boston, and select either the square or polygon tool, the  Boston box returns and is apparently used in the query, even if I draw a second box. That's as near as I can tell by visiting the query again via the view link on the active searches page.

This may not provide any information, but currently the most recent several searches on the active searches page were created this way, eg:

 http://gimmefreshdata.github.io/?lat=42.31&limit=20&lng=-71.05&taxonSelector=Aves%2CInsecta&traitSelector=&wktString=GEOMETRYCOLLECTION%28POLYGON%20%28%28-72.147216796875%2041.492120839687786%2C%20-72.147216796875%2043.11702412135048%2C%20-69.949951171875%2043.11702412135048%2C%20-69.949951171875%2041.492120839687786%2C%20-72.147216796875%2041.492120839687786%29%29%2CPOLYGON%20%28%28-77.57171630859375%2038.56964280859044%2C%20-77.57171630859375%2039.12579898118164%2C%20-76.50604248046875%2039.12579898118164%2C%20-76.50604248046875%2038.56964280859044%2C%20-77.57171630859375%2038.56964280859044%29%29%29&zoom=7

**Comment by jhpoelen** [comment]
To delete an existing selection, click the trashcan icon, select the shape to be deleted, and click on "save".

Please let me know if that works for you. I was able to delete the boston default area with this recipe (for result see [here](http://gimmefreshdata.github.io/?lat=42.31&limit=20&lng=-71.05&taxonSelector=Aves%2CInsecta&traitSelector=&wktString=POLYGON%20%28%28-77.57171630859375%2038.56964280859044%2C%20-77.57171630859375%2039.12579898118164%2C%20-76.50604248046875%2039.12579898118164%2C%20-76.50604248046875%2038.56964280859044%2C%20-77.57171630859375%2038.56964280859044%29%29&zoom=5))

**Comment by jhammock** [comment]
Yes, I get it now. Arg, technology.

**Comment by jhpoelen** [comment]
Glad you got it to work. To be honest - it wasn't quite clear to me either. Please re-open the issue if this functional yet confusing add/delete functionality is causing too much frustration.
