### ISSUE TITLE
Unexpected behaviour when using browser back/forward 

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#2]
In Chrome, OS X 10.10.5

Browser back/forward behavior is more complicated but seems related: If one query is followed by a different query in the same browser window, stepping backward to the old query (usually requiring several steps probably corresponding to query refreshes) eventually produces a url for the new query but map and results for the old query (mismatch1). Stepping forward again eventually produces the url for the old query and the map and results for the new query.

Stepping a little farther in either direction seems to complete the transition, bringing url in line with the other changes.

![mismatch1](https://cloud.githubusercontent.com/assets/3026567/13791908/afc90b98-eac5-11e5-841a-f60e4f08665b.jpg)
![mismatch2](https://cloud.githubusercontent.com/assets/3026567/13791913/b38e6728-eac5-11e5-945c-853530904b76.jpg)

**Comment by jhpoelen** [comment]
If I understand it correctly, these are two separate issues: (1) resize in chrome changes search criteria and (2) using back button in chrome causes unexpected behavior.

**Comment by jhpoelen** [comment]
root cause of unexpected behavior was the way in which the spatial selection was calculated.

Now, a new method is used, and this should no longer occur. Please re-open/comment if the issue persists.
