### ISSUE TITLE
number of occurrences in results header may not reflect addedAfter filter

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#21]
see for instance: 

http://gimmefreshdata.github.io/?addedAfter=2016-01-01&lat=42.31&limit=20&lng=-71.05&taxonSelector=Sciuridae&traitSelector=&wktString=POLYGON%20%28%28-72.147216796875%2041.492120839687786%2C%20-72.147216796875%2043.11702412135048%2C%20-69.949951171875%2043.11702412135048%2C%20-69.949951171875%2041.492120839687786%2C%20-72.147216796875%2041.492120839687786%29%29&zoom=7

header reads "Occurrences [361] matching occurrences (first 20 shown below)"

The csv download (50 records) and displayed results both appear to be properly constrained, but if the count is reflected anywhere in the services, that should probably be brought into line

**Comment by jhpoelen** [comment]
@jhammock as you observed, the record count in the table header includes _all_ records within specified taxon and geospatial selection. Detecting the changes by diff-ing by added date filters the top 20 and associated download, but does not change the number of records. Perhaps we can discuss a bit on how to best display this in the web prototype.

**Comment by jhammock** [comment]
at your service :)

**Comment by jhpoelen** [comment]
Settled on wording be changed to something like: 

a total of [number of records records] matching occurrences. . . were included this search. ... save all records as csv 

if first added date has been added:

a total of [number of records records] matching occurrences. . . were included this search. ... save all records as csv or save all records added after [date] and before [date] as csv.

**Comment by jhpoelen** [comment]
implemented as suggested.
