### ISSUE TITLE
allow for selecting occurrences by eventDate as range

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/freshdata#22]
data sources provide a dwc:eventDate . This field is translated into eventDateStart/End, because the eventDate may or may not represent a date range. The eventDateStart is currently displayed in the top 20 sample table in prototype search web page at http://gimmefreshdata.github.io . @mxweber suggested constrain the records of interest to only include those within a specific range of the eventStartDate. Note that this should not be confused with the firstAddedDate, which represents the date at which the record was first added to fresh data.

**Comment by jhpoelen** [comment]
@jhammock would you imagine to this be used for the diff sub-selection or for the main search selectors (e.g. taxon, geospatial)?

**Comment by jhammock** [comment]
Main search selectors. Some people may be looking eg: for seasonal shifts in migration or emergence. Let's not get fancy and enable the same season in multiple years, though. Next version.

**Comment by jhpoelen** [comment]
implemented as suggested.
