### ISSUE TITLE
review first pass of freshdata api documentation

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/freshdata#23]
@jhammock as discussed, please solicit reviews to the first pass at the api documentation here: https://github.com/gimmefreshdata/freshdata/wiki/api . Please feel free to edit/update in the wiki (anyone can edit). This api should be able to cover the fresh data use cases.

**Comment by jhammock** [comment]
This looks great! It was human readable, even for @jhammock. I would like to reach out to a couple of partners (data provider, data consumer, and EOL integrator) for review. OK to proceed?

(I know we're still waiting on the queries-of-subscribed-records layer, but I think this is enough to be starting with for everyone- yes?)

**Comment by jhpoelen** [comment]
@jhammock would be great to get a first pass at the reviews from partners. I'd be particularly interested how they'd like to get notified of changes, particularly in the server-to-server communication).
