### ISSUE TITLE
url shortening of search links

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/freshdata#24]
Katja Seltmann suggested to shorten the urls used to point to searches.

**Comment by jhpoelen** [comment]
Shelley reported that "long" urls in notification email are chopped up in such a way that they no longer work. (see attached screenshot, notice the extra `=`).
![screen shot 2016-06-02 at 9 33 20 am](https://cloud.githubusercontent.com/assets/1084872/15752896/14c0aba6-28a5-11e6-8a74-abf4d368becd.png)

**Comment by jhpoelen** [comment]
Introduced uuids for queries/ selectors in an effort to shorten the notification urls. 

Now the notification email look like the attached screenshot:
![screen shot 2016-06-03 at 6 34 40 pm](https://cloud.githubusercontent.com/assets/1084872/15796777/ebcf39f4-29b9-11e6-8e3a-f612481d91c3.png)

**Comment by jhammock** [comment]
Hmm... is the UUID really the format we want to use in examples in the API documentation? That makes it a bit tricky (for a novice) to construct a query for the first time without using both the prototype and the monitors list. I would go ahead and attempt edits, but I am a child in these matters and perhaps I'm wrong...
