### ISSUE TITLE
introduce webhook notification mechanism

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/freshdata#27]
currently, updates are notified by email.

@godfoder suggested to introduce webhooks also, using a url scheme provided by third-party and appending monitor parameters /uuids as query parameters.

**Comment by jhpoelen** [comment]
@godfoder Webhook are now enabled on subscription service. Endpoint can be provided through http://gimmefreshdata.github.io or directly using the subscribe endpoint.

Example: for endpoint `http://somehost`, the following http get request issued:

```
http://somehost/?taxonSelector=....&wktString=....&traitSelector=....
```

https://github.com/gimmefreshdata/freshdata/wiki/api will be updated accordingly.

Please re-open if you have comments/ change suggestions.

**Comment by jhammock** [comment]
This feature is retired. User platforms are expected to rely on the API.
