### ISSUE TITLE
Zoom on Chrome results in bbox change

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/freshdata#3]
from #2 

In Chrome, OS X 10.10.5

Zooming in and out of the browser window causes results to disappear. Refreshing either the query or the browser window brings them back

**Comment by jhpoelen** [comment]
I was able to reproduce this on Chrome. The same effect does not occur in Firefox v44.0.2 on mac os 10.11.3 . 

The root cause is that the third party widgets used to render the map (leaflet + plugin) detect the zoom in chrome as a change in selection area. As a result, the list is removed and the search url is updated. 

@jhammock Fixing this would require switching widgets or fixing the widgets. Please let me know how important this issue is for you.

**Comment by jhammock** [comment]
Not important; I noticed it by accident while composing a screenshot for https://github.com/gimmefreshdata/freshdata/issues/2  I can't imagine it happening hardly ever in a normal use case.

**Comment by jhpoelen** [comment]
root cause of unexpected behavior was the way in which the spatial selection was calculated.

Now, a new method is used, and this should no longer occur. Please re-open/comment if the issue persists.
