### ISSUE TITLE
/monitors and /monitoredOccurrences should count only queries that have been saved/subscribed/monitored

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#31]
Discussed with @jhpoelen but never recorded, I think. (Also, might be done already.) There should be a way to query /monitors and /monitoredOccurrences and get results related only to queries that have been turned into monitors (attached to an email address or webhook).

This can be the only possible result for both services, especially if that's easier. We are not committed to saving every query made, only those that are attached to notifications. It can also be a parameter, especially if that's easier.

**Comment by jhpoelen** [comment]
Thanks for jotting this down. Initial thoughts are to allow occurrence requests only if the user (e.g. person or machine) provide a way to notify of the results (e.g. email/webhook). If the monitoring entity is no longer interested, an unsubscribe request is issued which result in the removal of the monitors and its monitors occurrences from the usage reports. 

In short, the subscribe/unsubscribe actions will be used to activate or deactivate a monitor. Only monitored occurrences can be requested through /occurrences and only monitored occurrence are included in /monitors and /monitoredOccurrences . 

In this case, ad-hoc query support can be implemented by a subscribe/unsubscribe sequence.

@jhammock curious to hear your comments

**Comment by jhammock** [comment]
Interesting. I'm on the fence, I think. Things considered:
- I personally, at least, am primarily interested in subscribing searchers, not ad hoc searchers. 
- There is the use case of a searcher who will want to "check out the goods" first, before deciding to subscribe. This is a higher barrier for them.
- It will also encourage defaulting to subscribe rather than defaulting to ad hoc, which is good and bad (we'll get more serious monitors and more frivolous monitors).
- It feels a bit less "open". You must reveal your address-of-some-kind in order to get data. But, again, we're interested in subscribing searchers...

The real sticking point: If casual searchers use this method for an ad hoc search, presumably, data use notifications may be sent. This could lower the bar on the weight/relevance of the data use notifications, though perhaps only occasionally. It may depend on the frequency with which interested data providers check monitoredOccurrences vs the time window within which a casual searcher deactivates their monitor. 

Thoughts or corrections of my assumptions?

**Comment by jhpoelen** [comment]
I think this boils down to the definition of "usage". 

Would you considering someone poking around a user of data? Or how about a monitor being used by someone who never checks the notifications? Or a single person creating 20 monitors vs. 1 monitor being subscribed to by many folks. 

I'd say that the definition of data usage depends on the person/system using it. Assuming that most users would be actual systems (e.g. EOL using fresh data to setup monitors for its users), the systems themselves can monitor usage because they sit in the middle and observe how folks are using it. Perhaps worth a voice discussion to hash this out.

**Comment by jhpoelen** [comment]
After discussion, we decided to only include active monitors in the data usage reports, see #32 for more details.
