### ISSUE TITLE
make monitors disappear after 180 days of not being used

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/freshdata#32]
where used is requesting occurrences and/or subscribing.

**Comment by jhpoelen** [comment]
@jhammock monitors (and associated usage data) now disappear after 180 days of not being accessed. For testing purposes, you can add the query parameter `ttlSeconds=[some number]` to the occurrence request api calls `/occurrence`. 

An example to create a monitor that disappears 300 seconds (5 minutes) after being populated / updated would look something like: `/occurrences?limit=20&ttlSeconds=300&taxonSelector=Aves%2CAraneae%2CMuridae&wktString=POLYGON%20((-122.6733398374999%2037.56199695314352%2C%20-123.04687499999999%2038.28418778704841%2C%20-121.56372070312499%2038.28418778704841%2C%20-121.95922851562501%2037.4530574713902%2C%20-122.67333984374999%2037.56199695314352))`

Please re-open this issue if you encounter unexpected behavior.

**Comment by jhammock** [comment]
This works. My Queensland Amphibians have disappeared from the monitors list :)
