### ISSUE TITLE
optional self-identification field for queries

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#36]
Could an optional parameter (if that's the word I want) be added to /occurrences that simply stores a text string, associated with that query and delivered with it in /monitors ? This would allow searchers to informally self identify if they choose, and in some cases (eg: EDDMapS, SciStarter) allow convenient clustering/filtering within a large set of queries.

**Comment by jhpoelen** [comment]
@jhammock is this covered by Eli's Monitors V2? If so, please close this issue.
