### ISSUE TITLE
ensure that monitors and associated results survive a server restart

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/freshdata#37]
On restarting the server running freshdata services, previously created monitors disappear. This is due to a configuration setup with cassandra (the data store). 

We'd like to setup the services such that monitors and their associated results persist across restarts.

**Comment by jhpoelen** [comment]
related issue https://issues.apache.org/jira/browse/MESOS-1554

**Comment by jhpoelen** [comment]
Note that when cassandra runs in a cluster and rolling reboots are applied, cassandra itself should take care of keeping the data around. However, in combination with mesos, the cache will be lost as part of mesos task garbage collection if all nodes get restarted at the same time.

**Comment by jhpoelen** [comment]
Looks like Marathon 1.1+/ Mesos 0.28+ support desired functionality in the form of persistent volumes. 

@godfoder @mjcollin any chance I can help setup the newer versions onto cluster instead of single node at acis? This way, we'd kill two birds with one stone: support persistent volumes and move to true clustered environment. Please advise.

**Comment by jhpoelen** [comment]
see https://mesosphere.github.io/marathon/docs/persistent-volumes.html for persistent volume info.

**Comment by godfoder** [comment]
Spark won't work with mesos > 0.24 at all, and is recommended with mesos
0.21. (yes, thats very old)

Our current plan is to run 9/14 blades as spark, and the other 5 as a
kubernetes cluster for container hosting.

**Comment by jhpoelen** [comment]
@godfoder checked some docs and found stuff like `Spark 2.0.0 is designed for use with Mesos 0.21.0 or newer and does not require any special patches of Mesos.`. Note the "or newer" part. Also, here's a blog post about running spark 1.6.1 on mesos 0.28.2 . Haven't tried it myself, but it looks pretty promising to me.

**Comment by jhpoelen** [comment]
I'll poke around a bit and see whether I can make this working on the current system. . .

**Comment by godfoder** [comment]
So the problem is this:

https://issues.apache.org/jira/browse/SPARK-11183

Obviously this is possible, so I just need to figure out how. Git master
for spark has this updated to the new mesos 1.0 bindings, but sadly it isnt
in the released version

https://github.com/apache/spark/blob/v2.0.0/pom.xml

https://github.com/apache/spark/blob/master/pom.xml

I'll see what I can do. I don't really want to have to hand build spark,
but I might need to.
- Alex

**Comment by jhpoelen** [comment]
I ended up just solving the problem by making automated backups of queries and subscriptions into `/home/int/backup` folder (is there a way to back this up beyond the server?). This are very lightweight files as they do not contain queries results. These results can be recreated with the data archives. 

So, for now, we at least have another way to (manually) recover the a valuable part of fresh data: the users and their monitors/searches/subscriptions. Perhaps good to follow path of least resistance. Also, if we run cassandra across nodes in a cluster, we should have enough redundancy to reduce chance of data loss.

**Comment by jhpoelen** [comment]
Cassandra now runs outside of Marathon as a plain old service. Restarting the service does not wipe out the data, so this issue has been resolved.
