### ISSUE TITLE
search should be case insensitive

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#39]
http://gimmefreshdata.github.io/?limit=20&taxonSelector=aphaenogaster%20picea%2Caphaenogaster%20fulva%2Caphaenogaster%20rudis&traitSelector=&wktString=POLYGON%20%28%28-138.8671875%2044%2C%20-138.8671875%2070%2C%20-47.8125%2070%2C%20-47.8125%2044%2C%20-138.8671875%2044%29%29

returns two records from GBIF with taxon name = aphaenogaster picea, but

http://gimmefreshdata.github.io/?limit=20&taxonSelector=Aphaenogaster%20picea%2CAphaenogaster%20fulva%2CAphaenogaster%20rudis&traitSelector=&wktString=POLYGON%20%28%28-138.8671875%2044%2C%20-138.8671875%2070%2C%20-47.8125%2070%2C%20-47.8125%2044%2C%20-138.8671875%2044%29%29

does not include them. Case _never_ provides useful information in a taxon name and we can expect it to be irregular.

**Comment by jhpoelen** [comment]
I could argue that making the searches case insensitive turns the exact matches into fuzzy matches. I'd argue that "homo sapiens" and "Homo sapiens" are really two very different things. Let us discuss by voice.

**Comment by jhammock** [comment]
Addressing this by inserting the GN Parser before harvested data and searcher input. The capitalization issue will be taken up with GNA if needed.

**Comment by jhpoelen** [comment]
@jhammock I changed my mind on this. Now, the taxon selector is case insensitive as you requested.  Also see #47 . Will close issue as soon as changes have propagated to the monitors.

**Comment by jhammock** [comment]
That works for me; thanks for the update!

**Comment by jhpoelen** [comment]
Changes have propagated. Now, both `aphaenogaster picea|aphaenogaster fulva|aphaenogaster rudis` and `Aphaenogaster picea|Aphaenogaster rudis|Aphaenogaster fulva` yield the same results.
