### ISSUE TITLE
time stamp for status of search / progress bar

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#4]
Could we have in the brackets something like [I have been working on your occurrences for n minutes] ?

**Comment by jhpoelen** [comment]
Sounds like a good idea. We'd need to record the time at which a search was created for other use cases also. More later...

**Comment by jhpoelen** [comment]
re-iterated by Andrea Wiggings in todays review meeting.

**Comment by jhpoelen** [comment]
covered by %complete status.
