### ISSUE TITLE
revisions to NEON archive

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#42]
A draft of this archive is up which possibly still needs some work. The file extension on the observations file is txt, which might be fine. We'll see if Jen messed up anything else in the meta. The field index=0 cells are empty. A 32 digit string, the only identifier produced by NEON, is used in field index=1, occurrenceID. How is all of that?

Finally: there is no url associated with a single record on NEON, so the only available information to provide provenance is the project identity and URL, which is in the source column of this dataset record in the Archives index. If this url were provided in the Occurrences and MonitoredOccurrences services instead of or in addition to the source label, that might be the easiest way to provide provenance in these cases. Other ideas?

Please assign this ticket to @jhammock with instructions for revisions needed :)

**Comment by jhammock** [comment]
http://data.neonscience.org/browse-data

**Comment by jhammock** [comment]
meta is now meta.xml, ready to try rebuild (unless I can be permitted to rebuild it :)

**Comment by jhpoelen** [comment]
@jhammock  It appears that the meta.xml contains weird quotes:

```
fieldsTerminatedBy=“/t“
```

Please replace the quotes with regular quotes (e.g. `"`) , rebuild archive and trigger new build.

**Comment by jhammock** [comment]
done, build scheduled but it seems to be taking a moment

**Comment by jhpoelen** [comment]
issue moved to https://github.com/gimmefreshdata/source-neon/issues/1 . Closing this one.
