### ISSUE TITLE
Provide source url if constructed-from-occurrence-ID url is not available

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#45]
This came up in discussion of https://github.com/gimmefreshdata/freshdata/issues/42 and I believe a simple solution was imagined, but I'm not sure what the implementation was. I would be happy if the generic source link (the one associated with the whole archive, which lives somewhere in the Jenkins profile now, I think...) showed up either
-in all records as a new column
-in records lacking an occurrence-ID-generated url, in the occurrenceURL column (this seems like more work)

Just in the services, not in the prototype display

**Comment by jhpoelen** [comment]
@jhammock I've made it so that whenever a occurrence id url scheme is not available it points to appropriate archive job at http://archive.effechecka.org .

**Comment by jhammock** [comment]
Looks good! Descriptions added.
