### ISSUE TITLE
Update of NEON may be hung up at dwc2parquet

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#48]
I updated [this resource](http://archive.effechecka.org/job/neon/) with added ancestry in the observations file. 

First attempt: I missed an element in the meta file. 
2nd attempt: weird quotation marks snuck in again.
[current attempt](https://github.com/gimmefreshdata/source-neon/blob/master/Jenkinsfile): I swear I can't see anything wrong with it, but it is, I think, hung up at dwc2parquet

There may be other requirements for the resource that I am missing, but looking through the most recent attempt, handily documented in https://github.com/gimmefreshdata/freshdata/issues/47, I don't see anything... 

Also possible that my inaugural use of "abort" has screwed something up?

**Comment by jhpoelen** [comment]
Thanks for sharing. From http://archive.effechecka.org and associated logs, I can see that the neon import is patiently waiting for http://archive.effechecka.org/job/update%20monitors/ to complete. The periodic update of inaturalist (http://archive.effechecka.org/job/inaturalist/) triggered the update of the monitors. 

So, to make a long story short, the system is behaving as expected and is pretty busy, adding to an already warm server room in Gainesville, FL.

**Comment by jhpoelen** [comment]
@jhammock please ping me if you need more info / explanation.

**Comment by jhammock** [comment]
Cool! I saw the other processes running in those snazzy new parallel lanes, but I did not expect the waiting to start in that step.

**Comment by jhpoelen** [comment]
PS I would expect that the wait time will be reduced when we switch over to the @godfoder / @mjcollin mega-cluster .
