### ISSUE TITLE
Results do not show up unless reload the page

### ISSUE THREAD

**Issue by yrhe** [gimmefreshdata/freshdata#5]
For the latest version of Freshdata prototype that Jen notified us on March 16, I've tired to search a few times. After I clicked "request occurrences", the statuses for these searches became [working on your occurrences...], but did not change anymore and did not show any results. Then I found that if I wait long enough and manually reload the webpages, the results (e.g., a list, or notification of no items) would show up.

**Comment by jhpoelen** [comment]
@yrhe thanks for your feedback. I am glad to hear your were able to retrieve the occurrences. Also, I can see how clicking the "refresh" button or refreshing the page is a functional, but not quite gratifying user experience. One way to address this is to populated the occurrence list whenever the results are available (see https://github.com/jhpoelen/effechecka/issues/12 for similar idea for checklist use case) . Hoping to discuss this during our call today.

**Comment by yrhe** [comment]
Hi Jorrit,

Thank you very much for your reply! Yes, looking forward to discussing with
you in our meeting today.

Best wishes
Yurong

**Comment by jhpoelen** [comment]
Page now refreshes once the results are available. Please re-open/ comment when the page does not load the newly available data.
