### ISSUE TITLE
NEON data replaced with ancestry; search by ancestor not returning children

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#51]
This is the monitor I'm using: http://gimmefreshdata.github.io/?limit=20&taxonSelector=Culicidae&traitSelector=&wktString=POLYGON%20%28%28-135.087890625%2023.88583769986199%2C%20-135.087890625%2051.83577752045248%2C%20-52.82226562499999%2051.83577752045248%2C%20-52.82226562499999%2023.88583769986199%2C%20-135.087890625%2023.88583769986199%29%29

The NEON resource (http://archive.effechecka.org/job/neon/) was replaced a couple of days ago, and I believe a number of records  should now include Culicidae as an ancestor, but the only NEON record returned by the search above has Culicidae in the ScientificName.

**Comment by jhpoelen** [comment]
@jhammock thanks for sharing your query. I downloaded the occurrences.tsv associated to the query, and I found the one record you ref:

```
Culicidae sp.   Animalia|Arthropoda|Insecta|Diptera|Culicidae sp.       32.97357        -87.408875      2014-06-04T00:00:00.000Z        C91E2F2BAE094A648C1DBA02220D18D9        2016-08-22T00:00:00.000Z        neon    
```

Inspecting the newer neon.zip archive (downloaded today), more Culicidae records do appear. Note that the first added date of this record is 22 Aug 2016. More soon . . .

**Comment by jhammock** [comment]
Ah. That first added date sounds much more like an earlier version of NEON. Perhaps my updated file didn't make it...

**Comment by jhpoelen** [comment]
After some digging, I found the root cause: freshdata does currently not consider a taxon field / column if it is not defined by _all_ data sources. It turns out that one of the order neon archive did not include the "family" columns. 

Turns out that a Apache Spark feature called "schema merging" was disabled by default after v.1.5.0. I'll enable the feature for now.

**Comment by jhpoelen** [comment]
Feature has been enabled. Changes should propagate to monitors after http://archive.effechecka.org/job/update%20monitors/19/ has completed. Will check and comment on results when the job has completed.

**Comment by jhpoelen** [comment]
@jhammock still working on it.

**Comment by jhpoelen** [comment]
Turns out that https://github.com/gimmefreshdata/source-neon/issues/2 was the root cause of this issue: due to invalid eventDate format, the recent data from neon was ignored all-together, leaving only the older occurrence data (e.g. 17 Aug 2016) as candidates for fresh data monitors.

**Comment by jhpoelen** [comment]
Unfortunately, http://tools.gbif.org/dwca-validator does not check the date format.
