### ISSUE TITLE
Notification should include a query link for "just the new records"

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#52]
I think we discussed this but never documented it. And I _think_ that new-records link was to be instead of the all-records link, rather than in addition (but as usual, I'm on the fence about this and could be talked into either.)

Now that I think about it, there's a complication, I think. We're relying on someone visiting their all-records link when they get notifications in order to keep their monitor alive. Will this still work if they habitually visit the new-records link instead? (Or perhaps: can it be arranged that any value of the addedAfter parameter is permitted to keep a given monitor alive?)

If that's a pain, we can add text to the notification explaining that they should gloat over ALL their data every so often if they want notifications to continue. And advise webhook users (eg: EDDMaps) to do the same.

**Comment by jhpoelen** [comment]
A monitor will be kept around for all and/or new record queries happen at least once every 180 days. So, the answer to your question "Will this still work if they habitually visit the new-records link instead? " is: yes! 

Please let me know if you still see an issue, if so, please provide the proposed email body/subject. If not, please close the issue.

Thanks!

**Comment by jhammock** [comment]
Good! But I think the easy part remains to be done. This is my mosquito notification from a few days ago:

---

Hi!

New data is available for a freshdata search you subscribed to. Please see http://api.effechecka.org/view?uuid=e0b5bb53-04e9-56d6-8e15-062a3ef1f77b for more details.

If you no longer wish to receive these email, please visit http://api.effechecka.org/unsubscribe?subscriber=mailto%3Ajen.hammock%40gmail.com&uuid=e0b5bb53-04e9-56d6-8e15-062a3ef1f77b .

Thanks!

PS Fresh Data is an early stage prototype. Please share your feedback at https://github.com/gimmefreshdata/freshdata/issues/new .

---

The UUID points to 

http://gimmefreshdata.github.io/?limit=20&taxonSelector=Culicidae&traitSelector=&wktString=POLYGON%20%28%28-135.087890625%2023.88583769986199%2C%20-135.087890625%2051.83577752045248%2C%20-52.82226562499999%2051.83577752045248%2C%20-52.82226562499999%2023.88583769986199%2C%20-135.087890625%2023.88583769986199%29%29

while I imagine it aught to point to

http://gimmefreshdata.github.io/?addedAfter=2015-09-16&limit=20&taxonSelector=Culicidae&traitSelector=&wktString=POLYGON%20%28%28-135.087890625%2023.88583769986199%2C%20-135.087890625%2051.83577752045248%2C%20-52.82226562499999%2051.83577752045248%2C%20-52.82226562499999%2023.88583769986199%2C%20-135.087890625%2023.88583769986199%29%29

or perhaps what I am seeing is a "first notification artifact", and future notifications for this monitor will come with an AddedAfter parameter in the link?

**Comment by jhpoelen** [comment]
@jhammock I included the `addedAfter` parameter as requested. Please close this issue if you confirmed that this feature is now working as expected.

**Comment by jhammock** [comment]
cool; I believe I will be able to confirm this when #51 is resolved; that should produce a Not First notification to my address.

**Comment by jhpoelen** [comment]
@jhammock note that addressing #51 will not necessarily send a notification, because the date of ingestion of the archive is used to determine the first available date. However, you can trigger notifications for an arbitrary date using the notification api as used by http://archive.effechecka.org/job/notify%20subscribers/ .

**Comment by jhpoelen** [comment]
For docs see https://github.com/gimmefreshdata/freshdata/wiki/api#notify . Added some description for addedBefore / addedAfter.

**Comment by jhammock** [comment]
Today's monitors update fired off several notifications complete with links to data since september 16

**Comment by jhpoelen** [comment]
I received some more updated for neon updates added 22 Sept 2016, and 
expect that more will follow triggered by the same 22 Sept 2016 update. 
I imagine still might confuse the user. Perhaps a better way to trigger 
updates is after the addition of new data. Will open new issue soon.

**Comment by jhammock** [comment]
Okay, standing by. I do think this issue would be resolved if the freshness window were equal to the interval since the last set of notifications...

**Comment by jhpoelen** [comment]
Closing this issue. See #56 for new issue mentioned in comments.
