### ISSUE TITLE
search without taxonomic filter?

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#53]
This may be possible already, and I just don't know how to construct the query. I would like to be able to search for all biota within a region. Is it possible to have a search without a taxonomic filter, which fetches relevant records for any and all taxa?

**Comment by jhpoelen** [comment]
Currently not possible by design. Not a technical issue, more of a way to discourage downloading ~1B occurrence records. Perhaps worth a discussion to revisit this somewhat arbitrary constraint.

**Comment by jhammock** [comment]
Ah, that makes sense... Alas, some small regional searches may be this taxonomically broad. Not to mention, selecting a couple of kingdoms fairly easily circumvents this as a constraint for large volume queries. I like the fact that the restriction kicks in before the query does the work of finding out how crazy a number of records you want, though.

Perhaps a secret taxon filter value, which would become an open secret if people browse the monitors, but would make it just a little harder? Or a [taxon black list] X [polygon size] restriction? Harder to explain to users, but it could throw an error message, "you cannot haz Animalia from such a large region" or words to that effect...

Or a record limit, if it is not such a drawback to be forced to come up with N records before saying N+1 is too many?

**Comment by jhammock** [comment]
This is becoming an important piece of functionality, although the 3 kingdom workaround is not terrible for this use case: We'd like to incorporate effechecka into the new EOL search as the geographic filter (using a specified list of cached queries for starters). Queries w/o taxon filter would be ideal for this.

**Comment by jhpoelen** [comment]
As requested by @jhammock , taxonomic selectors can now be empty. An empty taxon selector will accept records with any taxa.
