### ISSUE TITLE
expected GBIF results not found in Fresh Data

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#55]
These are bird data, from various sources via GBIF (mostly but not entirely from eBird, if it matters). Some results are found on GBIF for similar (I tried to make them subset) polygons. The species names present differently, but I am surprised if the canonical names in Fresh Data don't retrieve the corresponding GBIF names...

Monitor: http://gimmefreshdata.github.io/?limit=20&taxonSelector=Puffinus%20puffinus&traitSelector=&wktString=POLYGON%20%28%28-154.68749999999997%2035.460669951495305%2C%20-154.68749999999997%2062.2679226294176%2C%20-112.5%2062.2679226294176%2C%20-112.5%2035.460669951495305%2C%20-154.68749999999997%2035.460669951495305%29%29

GBIF search: http://www.gbif.org/occurrence/search?TAXON_KEY=5229380&HAS_COORDINATE=true&HAS_GEOSPATIAL_ISSUE=false&GEOMETRY=-144.140625+60.239811%2C-144.140625+41.508577%2C-119.53125+41.508577%2C-119.53125+60.239811%2C-144.140625+60.239811

Monitor: http://gimmefreshdata.github.io/?limit=20&taxonSelector=Fratercula%20cirrhata&traitSelector=&wktString=POLYGON%20%28%28-78.046875%2030.44867367928756%2C%20-78.046875%2054.16243396806779%2C%20-21.4453125%2054.16243396806779%2C%20-21.4453125%2030.44867367928756%2C%20-78.046875%2030.44867367928756%29%29

GBIF search: http://www.gbif.org/occurrence/search?TAXON_KEY=2481357&GEOMETRY=-71.015625+49.152969%2C-71.015625+39.368279%2C-38.320312+39.368279%2C-38.320312+49.152969%2C-71.015625+49.152969&HAS_COORDINATE=true&HAS_GEOSPATIAL_ISSUE=false

**Comment by jhpoelen** [comment]
Root cause it that GBIF reports scientific name as "Puffinus puffinus (Brunnich, 1764)" and search is performed on "Puffinus puffinus". Canonical name support is hopefully provided through gnparser of global names sometime in the (near) future. Once the gnparser matures (see for example outstanding bug https://github.com/GlobalNamesArchitecture/gnparser/issues/309), the library can be used to make fresh data taxon matching a little more robust. Curious to hear your thoughts on this.

**Comment by jhammock** [comment]
Ah. So, there is currently no way to search for species like this example by name in Fresh Data. Entering a string that includes an authority in parentheses appears to break something, in both the prototype and the /occurrences service. Is the GNA the source of that? I would certainly rather rely on their effort than patch over it. 

That being said, the reason I expected this to work (that is, expected entering the canonical name to fetch the name & authority records) was a patch I think you made in order to find species names using a genus search term. I assumed that was a simple substring match, which I think would catch these cases too, and infraspecific taxa for a species search, come to that. I gather it was somewhat more specific to the genus -> species case?

**Comment by jhpoelen** [comment]
@jhammock I can see how it is a bit of a bummer to not be able to search by canonical names. I put in a workaround until a better and much improved taxonomic name parser becomes available.

For now, the taxonomic matching algorithm not only includes complete taxon names, individual words but also so-called bigrams.

What happened in our example is the following:

Source reported a bunch of `Puffinus puffinus (Brunnich, 1764)` whereas the monitor specified `Puffinus puffinus`. 

Previously, the taxon selector of fresh data would consider a match if:

`Puffinus puffinus` would match `Puffinus puffinus (Brunnich, 1764)` or `Puffinus` or `puffinus` or `(Brunnuch` or ... . 

Now, the taxon selector, considers adjacent word combos (aka bigrams) also, so taxon selector would include if:

`Puffinus puffinus` matches  `Puffinus puffinus (Brunnich, 1764)` or `Puffinus` or `puffinus` or `(Brunnuch` or `Puffinus puffinus` or `puffinus (Brunnich` or ....

I hope this patch is suitable for the time being. If not, please holler.

PS I'll trigger a fresh monitors shortly and share url.

**Comment by jhpoelen** [comment]
Just scheduled `fresh monitors` build number 23 . Has to wait until the previous one proceeds. That one was trigger by the weekly iNaturalist import.

**Comment by jhpoelen** [comment]
see http://archive.effechecka.org/job/update%20monitors/

**Comment by jhpoelen** [comment]
The changes have propagated to the monitors. Please confirm that results are expected by closing this issue.

**Comment by jhammock** [comment]
Beautiful patch, thanks. Subspecies, weird subspecies, authority labels, all neatly fetched. Who needs GNA? (kidding)
