### ISSUE TITLE
move freshdata services to idigbio cluster

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/freshdata#58]
Move some, or perhaps all, of freshdata services to idigbio managed mesos cluster.

subtasks include: move spark jobs, move data archives, configure cassandra to be accessible from the spark jobs, figure out how to run web api (e.g. api.effechecka.org) such that it can access cassandra (for results), the internet (to send email notifications, webhook events), as well as spark cluster (to launch jobs).

@jhammock yet another possible task for EOL engineer to take on and familiarize with freshdata infrastructure.

**Comment by jhpoelen** [comment]
depends on #57 to be completed.

**Comment by jhpoelen** [comment]
@jhammock let me now how I can help with getting Eli up to speed on this. Perhaps we can devise a step-by-step plan for the transition?

**Comment by jhpoelen** [comment]
@eliagbayani @jhammock #57 has been completed, so the move can start. Suggest to first complete #61 and update jenkins scripts for archive manager to write to hdfs instead of local disk. Once this is done, we can switch to using hdfs instead of local disk on existing server by changing how api is started (e.g. https://github.com/jhpoelen/effechecka/blob/master/run-hdfs.sh and https://github.com/jhpoelen/effechecka/blob/master/run.sh) on marathon.  After that, services like jenkins, cassandra, kafka, api and notifier can be moved such that the idigbio cluster can access them while running the spark jobs. Please ping me if you have any comments/questions about this.

**Comment by jhpoelen** [comment]
@jhammock effechecka api is now running on the cluster thanks to support by @godfoder and @mjcollin . 

The "old" server is still running cassandra. Also, while the archive jobs (archive importers) have been moved, we still need to get them working on hdfs. So, for the time being, the archive imports on archive.effechecka.org should still work, but need to be manually sync to be included in results of api.effechecka.org / api.guoda.bio . 

The first checklist generated  by this setup is one of ducks and frogs , see http://www.effechecka.org/?limit=20&taxonSelector=Anas%2CAnura&traitSelector=&wktString=POLYGON%20%28%28-72.147216796875%2041.492120839687786%2C%20-72.147216796875%2043.11702412135048%2C%20-69.949951171875%2043.11702412135048%2C%20-69.949951171875%2041.492120839687786%2C%20-72.147216796875%2041.492120839687786%29%29 .

**Comment by jhammock** [comment]
I love ducks and frogs!

I have no big plans for running an import job in the immediate future, but the "USGS Nonindigenous Aquatic Species" would make a reasonable test if a small resource is wanted at some point.

**Comment by jhpoelen** [comment]
Remaining tasks are documented in #61 and #67 . Closing this issue.
