### ISSUE TITLE
mailgun subscription needs maintanance

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/freshdata#62]
@eliagbayani @jhammock Freshdata email notifications are currently sent using mailgun. Action is required to keep this working. Perhaps best to switch to an EOL associated account. 

See the email I received below:
```
Hello,

We’re writing to let you know of several upcoming changes that may impact your Mailgun account.  This email contains a list of steps that you can reference that will help you determine if you need to make any changes to your configuration to continue using the service.

On November 1st, 2016:

Any domain created from this date forward will require verification through the use of a DKIM and SPF record to send and receive messages.
On December 1st, 2016:

All domains, regardless of the creation date, will be required to verify the domain to continue sending and receiving messages.
All subdomains of mailgun.org will be treated as sandbox domains, which are domains that allow sending to a list of up to five authorized recipients.
Mailgun is making these changes to our verification system to provide an additional proof of ownership check. Over the last several years, we've gradually increased the verification requirements based on industry best practices to ensure optimal deliverability.  These changes mean that all domains on your account will be handled consistently regardless of when they were created.

You can determine if these changes impact your account by following the steps below:

Checking for Unverified Domains

Login to the Mailgun control panel and select the Domains section.
Select any domain that is in the orange "unverified" state.  
In the Domain Verification & DNS section, locate the records with the red warning indicator.
In the DNS administration tool provided by your DNS or hosting provider, add all records under the section "DNS Records for Sending".   We have guides available that describe this process for the most common providers.
After the records have been added, click the "Check DNS Records Now" button.   Due to caching, up to 24 hours may be required before Mailgun is able to resolve the newly created records.
Once verification has been completed successfully, your domain will switch to a "verified" state.
Checking Sandbox Domains

Login to the Mailgun control panel.
Check for domains listed under the "sandbox domains" header on the dashboard home page.
Ensure that your application is not relying on any of the listed sandbox domains for sending and receiving.  If sandbox domains are being used, you must create a sending domain by clicking the "Add Domain" button under the sending domains section.
Additionally, you can use the logs and reporting features of the Mailgun control panel to determine what domains are actively sending and receiving messages on your account.  If you need assistance making these changes, please reach out to our support team by creating a ticket here.

Regards,

Josh Odom
Director, Product Development - Mailgun
www.mailgun.com
```

**Comment by jhpoelen** [comment]
@jhammock just a gentle reminder that freshdata email notification will likely stop working after Dec 1st unless action is taken.

**Comment by jhammock** [comment]
Thanks for the reminder, Jorrit; is ownership of the mailgun account something you can give to me or is it in your name?

**Comment by jhpoelen** [comment]
The mailgun account is coupled to the effechecka.org domain, which I own. Probably easier to create a new account or re-using an existing eol.org / idigbio email sending account and update the email configuration accordingly.

**Comment by jhammock** [comment]
Signup looks easy. I can only find one other reference to mailgun, at https://github.com/gimmefreshdata/freshdata/wiki/architecture. Is there a place where an account identifier needs to be swapped out, or is there something in your existing mailgun account that can be copied over to a new one?

**Comment by jhpoelen** [comment]
You can swap out the existing api key on the marathon configuration of the "effechecka-notifier" process. This configuration uses the startup script https://github.com/jhpoelen/effechecka/blob/master/runNotifier.sh with the api key as the first parameter. Once you have have the api key, I would stop the notifier by scaling it to "0" instances, then change edit the marathon configuration for effechecka-notifier by replacing the old key with the new one. After that, scale the process up to "1" to start the notifier.

**Comment by jhammock** [comment]
Thanks. @eliagbayani could you look into this? I thought my meagre skills might cover it but I think that's a dubious possibility while I'm on travel with half a brain...

**Comment by eliagbayani** [comment]
Sure. I think I know where to put the API from the Marathon configuration of the "effechecka-notifier".
Just send me the new API key. Thanks.

**Comment by jhammock** [comment]
Weird. Both Eli and I have had trouble getting a mailgun account to persist. (I was deactivated as a possible threat.) Jorrit, did you use the free version, or should we be investing in a paid one? Thanks!

**Comment by jhpoelen** [comment]
I do/did not pay for mailgun, so I am assuming I am in the free tier. Did you figure out why you were considered a potential threat?

**Comment by eliagbayani** [comment]
My Mailgun account is now active. That is after I sent an issue-ticket for their tech support.
And had some exchanges, answered their queries. 
https://mailgun.com/app/support/384018

**Comment by jhammock** [comment]
Oh good, thanks, Eli! Email alerts may become a thing for other kinds of EOL updates, so we may find additional uses for that account...

**Comment by eliagbayani** [comment]
Hi @jhammock , 
I successfully tested this mailgun account. I added my personal domain (elisysries.org) and updated some DNS entries for my domain and I was able to send emails using my personal domain (e.g. info@elisysries.org). I was able to do this because I own the account and I have access to its DNS settings (via web e.g. https://www.name.com/).

Now we will need this for the eol.org domain right. So instead of emails being sent by @effechecka.org it will become @fd.eol.org. "fd" stands for freshdata.
Is that the plan?

**Comment by jhammock** [comment]
good point. Yes, that sounds appropriate. Do we need someone to give you permissions for the eol.org domain, or are you empowered already?

**Comment by eliagbayani** [comment]
No power yet. Yes I need admin access to eol.org domain manager site. Thanks.
Basically, a username and password to administer the domain.

**Comment by jhammock** [comment]
Sorry to trouble you, @JRice, but I'm not sure where the eol.org domain is managed. Do you have the power to grant Eli access?

**Comment by JRice** [comment]
Aww, jeez. I dunno how to set that up. ...though I guess the "directions" should be out there somewhere. :S  We use Route 53.

I'll give it a shot.

**Comment by JRice** [comment]
Hello,

You have been given access to the AWS Management Console for the Amazon Web Services account ID ending in 8625. You can get started by using the sign-in information provided below.

Sign-in URL: https://eol-ops.signin.aws.amazon.com/console


Your initial sign-in password will be provided separately from this email. When you sign in for the first time, you must change your password.

Sincerely,

Your AWS Account Administrator

**Comment by JRice** [comment]
...let me know if that works... I sent the password to Eli in an email.  :S

**Comment by eliagbayani** [comment]
Thanks @JRice. Will give you feedback.
And yes, I got the email with password.

**Comment by eliagbayani** [comment]
I got in, found the DNS settings for eol.org (from AWS - Route 53). Nice. 
Getting late here, will proceed tomorrow. Thanks.

**Comment by eliagbayani** [comment]
Hi @jhammock, @jhpoelen, 
We now have info@fd.eol.org. You can test, run code below.  
Change the email recipient to point to your email (to=''), then run code in your terminal window.
Once you receive an email from info@fd.eol.org, you can even reply back and your email will be forwarded to: ("jen.hammock@gmail.com, jhpoelen@gmail.com, eagbayani173@gmail.com"). That is using Mailgun's 'routes' feature.

curl -s --user 'api:key-db412ea1ead52df7846edd8917d781c8' https://api.mailgun.net/v3/fd.eol.org/messages -F from='FreshData Info <info@fd.eol.org>' -F to='eagbayani@eol.org' -F subject='Hello' -F text='Testing some Mailgun awesomeness!'

Of course this also works for any ??????@fd.eol.org (e.g. noreply@fd.eol.org). But right now only info@fd.eol.org has a reply feature.

**Comment by eliagbayani** [comment]
Hi @jhpoelen 
I'm now ready to switch the API key on the marathon configuration of the "effechecka-notifier".
But is there a one place in FreshData codebase where "@effechecka.org" will be replaced by "@fd.eol.org". 
Thanks.

**Comment by jhpoelen** [comment]
@eliagbayani great to hear that you now have the api key. Please let me know if you have the required access to make the code changes. If so, please feel free to make the required changes. 

PS I would recommend asking mailgun to issue a new api key, because you just shared this secret with the world. Generally, I do not share passwords, api keys or anything "secret" in either github issues or email.

**Comment by eliagbayani** [comment]
@jhpoelen , I've now placed new key in 'cars', same folder as your 'flowers'.
Old key will expire in 48 hours.

I think I have access on the marathon configuration of "effechecka-notifier", that json entry.
But I don't know where to replace "@effechecka.org" with "@fd.eol.org".

**Comment by jhpoelen** [comment]
Great to hear you are making steady progress. As far as I know, you should be able to complete the email migration after applying some minor changes in https://github.com/jhpoelen/effechecka/blob/master/src/main/scala/effechecka/EmailUtils.scala . I've added you as a contributor to the repository.

**Comment by jhpoelen** [comment]
@eliagbayani good to see that you are making changes to effechecka! (see https://github.com/jhpoelen/effechecka/commit/b97d0f65230e5b615602ad68aa61a6aa65c6298d). 

Some notes:

**tests** Effechecka has automated (regression) tests that are executes every time the code changed. These tests are there to help prevent the introduction of bugs. The person fixing the build should receive a build notification by email (did you get one?). It is okay for the tests to fail, as long as there are fixed in less than a day. It seems that your commit broke the build (see https://travis-ci.org/jhpoelen/effechecka/builds/185972074). Let me know if you have any issues to getting the build to succeed again.

**link commit to issue** I try to link code changes to github issue whenever useful. You probably already know this, but for completeness: you can link a commit to an issue by putting a link to the issue in the commit comments.

**Comment by eliagbayani** [comment]
Hi @jhpoelen, fixed the tests. Travis build is now passing.

**Comment by eliagbayani** [comment]
Finally, I’m now receiving FreshData notifications using the new email: noreply@fd.eol.org.
```
e.g.
On Wed, Dec 21, 2016 at 11:08 PM, FreshData Notification (noreply) <noreply@fd.eol.org> wrote:
Hi!
You subscribed to the freshdata search available at http://api.effechecka.org/view?uuid=121d6828-28c5-5d6c-a569-c08370c4c971.
If you no longer wish to receive these email, please visit http://api.effechecka.org/unsubscribe?subscriber=mailto%3Aeli%40eol.org&uuid=121d6828-28c5-5d6c-a569-c08370c4c971 .
Thanks!
PS Fresh Data is an early stage prototype. Please share your feedback at https://github.com/gimmefreshdata/freshdata/issues/new .
```

**Comment by jhammock** [comment]
Me too!


---------- Forwarded message ----------
From: FreshData Notification (noreply) <noreply@fd.eol.org>
Date: Thu, Dec 22, 2016 at 9:29 AM
Subject: [freshdata] subscribed to freshdata search
To: jen.hammock@gmail.com


Hi!

You subscribed to the freshdata search available at
http://api.effechecka.org/view?uuid=7ac71647-d95e-5cc0-bb91-88f081eba703.

If you no longer wish to receive these email, please visit
http://api.effechecka.org/unsubscribe?subscriber=mailto%
3Ajen.hammock%40gmail.com&uuid=7ac71647-d95e-5cc0-bb91-88f081eba703 .

Thanks!

PS Fresh Data is an early stage prototype. Please share your feedback at
https://github.com/gimmefreshdata/freshdata/issues/new .

**Comment by jhpoelen** [comment]
@eliagbayani nice! Thanks for fixing the test. btw - it should be relatively straight forward to change the api.effechecka.org to something more appropriate. Perhaps something for later. It sounds like this issue can be closed to me.
