### ISSUE TITLE
archive.guoda.bio has failing jobs for idigbio and inaturalist 

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/freshdata#63]
See attached screenshot of http://archive.guoda.bio 

![screenshot from 2017-02-14 09-05-13](https://cloud.githubusercontent.com/assets/1084872/22939828/ce8e469c-f294-11e6-9739-37f2dd5980c8.png)

**Comment by jhpoelen** [comment]
see #78 for issue specific for update monitors.

@jhammock feel free to close this issue if inaturalist and idigbio updates are no longer needed through archive.guoda.bio .

**Comment by jhammock** [comment]
Ah, good question. I'm not relying on archive.guoda.bio to update resources. Are any of the routine jobs here not executable from commands I know in jupyter? I'm thinking of "janitor".

**Comment by jhpoelen** [comment]
Janitor was used to cleanup dangling items on the file system after updating resources through jenkins jobs. Since we no longer do this, janitor is no longer needed at this point.

**Comment by jhpoelen** [comment]
I've removed outdated jobs ```notify subscribers``` and ```janitor``` from archive.guoda.bio in addition to removing associated groovy scripts in https://github.com/gimmefreshdata/archive-importer .
