### ISSUE TITLE
queries >~200000 records: searches apparently complete, but records can't all be delivered

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#66]
tested by @eliagbayani. (Also by @jhammock, but in a web browser, so probably not useful.)

The JSON service can handle a higher number of records than the TSV.

limit=200K: success!

limit=500K: error message "The requested URL returned error: 504 Gateway Time-out"

(this is with paced requests. w/o and interval in between requests: error message
"The requested URL returned error: 503 Service Unavailable")

I imagine it is worth waiting to see if this changes after GUODA migrates. There could be Fresh Data use cases for queries of this size, which could be addressed with enhancements to the Fresh Data APIs if needed. Most Fresh Data "records delivered" are expected to be temporal diffs with much smaller numbers of records.

**Comment by jhpoelen** [comment]
Interesting - I'd expect the tsv to be able to handle more than json. If you'd like others to reproduce this (which query?, which endpoint?), you might want to consider some instructions on how to reproduce.

**Comment by jhammock** [comment]
It's not yet urgent, but here, in case it's interesting. It looks like there's variation among queries, or possibly among days, if my queries from yesterday are cached. 

Today's results are actually similar between JSON and TSV.

In a Chrome browser:

http://api.effechecka.org/occurrences.tsv?taxonSelector=Animalia%2CInsecta&wktString=POLYGON%20((-150%2010%2C%20-150%2040%2C%20-50%2040%2C%20-50%2010%2C%20-150%2010))

cuts off during the 4988th record of 111278193

http://api.effechecka.org/occurrences.tsv?limit=2000&taxonSelector=Animalia%2CInsecta&wktString=POLYGON%20((-150%2010%2C%20-150%2040%2C%20-50%2040%2C%20-50%2010%2C%20-150%2010))

returns complete results

http://api.effechecka.org/occurrences.tsv?limit=20000&taxonSelector=Animalia%2CInsecta&wktString=POLYGON%20((-150%2010%2C%20-150%2040%2C%20-50%2040%2C%20-50%2010%2C%20-150%2010))

cuts off after 4600 records

http://api.effechecka.org/occurrences?limit=2000&taxonSelector=Animalia%2CInsecta&wktString=POLYGON%20((-150%2010%2C%20-150%2040%2C%20-50%2040%2C%20-50%2010%2C%20-150%2010))

returns complete results

http://api.effechecka.org/occurrences?limit=20000&taxonSelector=Animalia%2CInsecta&wktString=POLYGON%20((-150%2010%2C%20-150%2040%2C%20-50%2040%2C%20-50%2010%2C%20-150%2010))

returns "There was an internal server error."

**Comment by jhammock** [comment]
Yesterday's query, I'm afraid, was a much longer polygon. Sorry. Running it now:

http://api.effechecka.org/occurrences?limit=200000&wktString=POLYGON%20((-81.17675811052322%2038.866147304827315%2C%20-80.45166045427322%2040.3724147137188%2C%20-78.64990264177322%2041.18766902511264%2C%20-76.56250029802322%2041.27029516213595%2C%20-74.69482451677322%2040.8893508055629%2C%20-74.16748076677322%2040.221587484085745%2C%20-74.91455107927321%2039.122307124684454%2C%20-75.70556670427322%2039.7670878257266%2C%20-75.57373076677322%2039.22451128580981%2C%20-75.24414092302322%2038.712006664146635%2C%20-75.55175811052322%2037.98828627141629%2C%20-76.05712920427322%2038.505967753770065%2C%20-75.94726592302322%2039.58105490004761%2C%20-76.32080107927322%2039.58105490004761%2C%20-76.65039092302322%2039.22451128580981%2C%20-76.56250029802322%2038.48877114593059%2C%20-76.47460967302322%2037.292324732564005%2C%20-76.80419951677322%2037.09979421886438%2C%20-76.03515654802322%2036.27165004883655%2C%20-78.91357451677321%2036.413239924092565%2C%20-80.80322295427322%2037.362214027755726%2C%20-81.17675811052322%2038.866147304827315))

returns complete results

http://api.effechecka.org/occurrences?limit=2000000&wktString=POLYGON%20((-81.17675811052322%2038.866147304827315%2C%20-80.45166045427322%2040.3724147137188%2C%20-78.64990264177322%2041.18766902511264%2C%20-76.56250029802322%2041.27029516213595%2C%20-74.69482451677322%2040.8893508055629%2C%20-74.16748076677322%2040.221587484085745%2C%20-74.91455107927321%2039.122307124684454%2C%20-75.70556670427322%2039.7670878257266%2C%20-75.57373076677322%2039.22451128580981%2C%20-75.24414092302322%2038.712006664146635%2C%20-75.55175811052322%2037.98828627141629%2C%20-76.05712920427322%2038.505967753770065%2C%20-75.94726592302322%2039.58105490004761%2C%20-76.32080107927322%2039.58105490004761%2C%20-76.65039092302322%2039.22451128580981%2C%20-76.56250029802322%2038.48877114593059%2C%20-76.47460967302322%2037.292324732564005%2C%20-76.80419951677322%2037.09979421886438%2C%20-76.03515654802322%2036.27165004883655%2C%20-78.91357451677321%2036.413239924092565%2C%20-80.80322295427322%2037.362214027755726%2C%20-81.17675811052322%2038.866147304827315))

fails

http://api.effechecka.org/occurrences.tsv?limit=2000&wktString=POLYGON%20((-81.17675811052322%2038.866147304827315%2C%20-80.45166045427322%2040.3724147137188%2C%20-78.64990264177322%2041.18766902511264%2C%20-76.56250029802322%2041.27029516213595%2C%20-74.69482451677322%2040.8893508055629%2C%20-74.16748076677322%2040.221587484085745%2C%20-74.91455107927321%2039.122307124684454%2C%20-75.70556670427322%2039.7670878257266%2C%20-75.57373076677322%2039.22451128580981%2C%20-75.24414092302322%2038.712006664146635%2C%20-75.55175811052322%2037.98828627141629%2C%20-76.05712920427322%2038.505967753770065%2C%20-75.94726592302322%2039.58105490004761%2C%20-76.32080107927322%2039.58105490004761%2C%20-76.65039092302322%2039.22451128580981%2C%20-76.56250029802322%2038.48877114593059%2C%20-76.47460967302322%2037.292324732564005%2C%20-76.80419951677322%2037.09979421886438%2C%20-76.03515654802322%2036.27165004883655%2C%20-78.91357451677321%2036.413239924092565%2C%20-80.80322295427322%2037.362214027755726%2C%20-81.17675811052322%2038.866147304827315))

cuts off during the 454th record

**Comment by jhammock** [comment]
I just unsuspectingly downloaded 5M records from 

http://gimmefreshdata.github.io/?limit=20&taxonSelector=Aves%2CInsecta&traitSelector=&wktString=POLYGON%20%28%28-72.147216796875%2041.492120839687786%2C%20-72.147216796875%2043.11702412135048%2C%20-69.949951171875%2043.11702412135048%2C%20-69.949951171875%2041.492120839687786%2C%20-72.147216796875%2041.492120839687786%29%29! 

(I was expecting the sample size). Possibly this issue can be closed?

**Comment by jhpoelen** [comment]
I'd say that the issue can be closed if previously reported unexpected behaviors can no longer be reproduced.

**Comment by jhammock** [comment]
Odd... I can still access the whole-result TSV for the query above, but this one doesn't behave the same. I tried inserting a limit=3000000 in the TSV link and either way I get the truncated results. Perhaps I should not be trying this yet.

http://gimmefreshdata.github.io/?limit=20&taxonSelector=&traitSelector=&wktString=POLYGON%20%28%28-76.6900634765625%2038.77978137804918%2C%20-76.640625%2038.91240739487225%2C%20-77.19268798828125%2039.34916646551957%2C%20-77.4810791015625%2039.11301365149975%2C%20-77.32040405273436%2039.052784883296624%2C%20-77.54150390625%2038.85682013474361%2C%20-77.22152709960938%2038.65870536210694%2C%20-77.19818115234375%2038.62008939987629%2C%20-77.07046508789061%2038.61257832462118%2C%20-76.89468383789062%2038.649053322140226%2C%20-76.74774169921875%2038.62116234642254%2C%20-76.74156188964844%2038.561321083266414%2C%20-76.68113708496092%2038.541720956040386%2C%20-76.6900634765625%2038.77978137804918%29%29

**Comment by jhpoelen** [comment]
Suggest to first finish the migration to hdfs before addressing this issue.

**Comment by jhpoelen** [comment]
Agree?

**Comment by jhpoelen** [comment]
see #67 and #61 .

**Comment by jhammock** [comment]
yes, that makes sense. I'll try again when migration is complete.

**Comment by jhpoelen** [comment]
@jhammock Suspect this issue was related to #70 . Please confirm.

**Comment by jhammock** [comment]
yes, thanks. I forgot this thread was still dangling.
