### ISSUE TITLE
include instructions on how to cite freshdata on gimmefreshdata.github.io (or related)

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/freshdata#68]
@diatomsRcool asked how to best cite freshdata. 

@jhammock any suggestions?

Probably best to have a little info page on how to cite freshdata and related datasets as part of gimmefreshdata.

**Comment by diatomsRcool** [comment]
My suggestion: Poelen et al. 2016. FreshData. http://gimmefreshdata.github.io

**Comment by jhammock** [comment]
Should it point to the search widget? We do expect it to persist, and it does have the menu items for those who want context, but I'd want people to be able to find their way to things like https://github.com/gimmefreshdata/freshdata/wiki/api also. Which maybe just means it should be linked to from other places...

**Comment by jhammock** [comment]
I went ahead and did that while I was updating the api wiki page. Now I like Ann's suggestion.

**Comment by diatomsRcool** [comment]
So who should be the authors and in what order?

**Comment by diatomsRcool** [comment]
This is the citation I am using
FreshData. https://github.com/gimmefreshdata/freshdata/wiki/api Accessed June 2017

**Comment by diatomsRcool** [comment]
This issue can be closed.
