### ISSUE TITLE
decommission Monitors API

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#69]
apologies if this duplicates another ticket. The Monitors v2 API is now switched to manual input, and existing monitors are cached. The original Monitors service can be switched off at any time.

**Comment by jhpoelen** [comment]
@jhammock great! Just curious - do you keep track of the monitor UUIDs also?

**Comment by jhammock** [comment]
Yes- and newly added monitors also get UUIDs, though you'd have to ask @eliagbayani about how that works. I don't imagine the new ones would yet be recognized by the monitoredOccurrences API, but they are available if we want to hook that together later.

**Comment by jhpoelen** [comment]
I imagine the monitor UUIDs are the ones that are the same as used by the services. They are derived from the query parameters and change whenever anything changes in the parameters. If we are talking about different UUIDs, no worries - they can live separately as long as we make sure not the mix the two. I just figured it might be nice to stick to once scheme.

**Comment by eliagbayani** [comment]
- the manually created monitors also have UUIDs. Just to differentiate it with the original monitors, the manually created monitors' UUID starts with "m-".
e.g. "m-b164cb45-8c06-427b-8f10-29269ab0800b"
Right now these UUIDs won't change, even when parameters change. Right now they serve only just as a regular ID for record maintenance.
- the existing monitors taken from the original monitors API would still use its original UUIDs. The admin interface can edit any field 
(Taxa, Status, No. of records, Trait_selector, String) except the UUID. Any change in the params won't change the UUID as well for now.

**Comment by jhpoelen** [comment]
Thanks for clarifying. From your description I learned that you have introduced a new kind of UUID in addition to the one that is derived from the content of the parameters. Personally, I would not mix the two in an effort to avoid confusion.

**Comment by jhpoelen** [comment]
It seems feasible to leave the monitors api around for now, but please don't rely on it. The current list may contain duplicates for monitors that have been updated.

**Comment by jhpoelen** [comment]
Closing issue - the monitors api can be considered decommissioned, as in nice to have, but can be dropped and should not be relied on for monitor persistence.

**Comment by eliagbayani** [comment]
Noted. Thanks for all the help @jhpoelen.
