### ISSUE TITLE
distinct fresh data request statuses

### ISSUE THREAD

**Issue by jhammock** [gimmefreshdata/freshdata#72]
It would be useful if the service returned status information distinguishing a query that has been successfully submitted from a query that must be re submitted before results can be made available. It would also be useful, though less important, if the status could distinguish between a query that has not yet succeeded because of rate limitation (which might resolve itself in minutes or hours) from a query that has not succeeded because there is no capacity available (admin intervention in the GUODA system may be needed.)

**Comment by jhpoelen** [comment]
Now, the messages from the spark job dispatcher are passed on. Now, whenever another job is already running the prototypes should show something like attached screenshot.

Please confirm and close issue.
![screenshot from 2017-07-12 16-43-58](https://user-images.githubusercontent.com/1084872/28144627-7f05c9b8-6721-11e7-9690-641508e4ab6a.png)

**Comment by jhammock** [comment]
hmm... When after a long break I refresh 

http://gimmefreshdata.github.io/?limit=20&taxonSelector=Lepidopa&traitSelector=&wktString=POLYGON%20%28%28-72.147216796875%2041.492120839687786%2C%20-72.147216796875%2043.11702412135048%2C%20-69.949951171875%2043.11702412135048%2C%20-69.949951171875%2041.492120839687786%2C%20-72.147216796875%2041.492120839687786%29%29

I get status=processing

If I refresh it again a few seconds later, I get status=Already reached maximum submission size. I expect that's a browser thing. Let me poke at the API call instead. I daresay that's more likely to be consistent

**Comment by jhpoelen** [comment]
Thanks for trying this. The behavior is working as expected, and we might be able to tweak the text to clarify.

Here's the flow - 

On requesting an unknown checklist/occurrence collection when no other jobs are running -> processing . 

On requesting an unknown checklist/occurrence collection when other jobs are running -> Already reached maximum submission size. This would include repeat requests for a job that is being processed.

Would it be more useful to say something like 'already processing this or other requests, please try again later.' ?

**Comment by jhammock** [comment]
new test:

http://api.effechecka.org/occurrences?limit=20&taxonSelector=Carnivora&traitSelector=&wktString=POLYGON%20%28%28-72.147216796875%2041.492120839687786%2C%20-72.147216796875%2043.11702412135048%2C%20-69.949951171875%2043.11702412135048%2C%20-69.949951171875%2041.492120839687786%2C%20-72.147216796875%2041.492120839687786%29%29

read "Already reached maximum submission size" for a couple of refreshes, then gave me results upon next refresh. Possibly I misunderstood. Does "Already reached maximum submission size" correspond to successful submission?

**Comment by jhpoelen** [comment]
"Already reached maximum submission size" indicates that a job is currently running. This running job may have been submitted previously by the (a) same query, or (b) an unrelated request (other occurrence list or checklist). So, in case of (a), a refresh with message "Already reaches ..." does imply that the request was submitted (as previously indicated by "processing") and is still running. 

Let me know if you'd like to switch to voice.

**Comment by jhammock** [comment]
Just one more sanity check- so now, "processing" means not submitted yet?

**Comment by jhpoelen** [comment]
In an effort to reduce confusion, I've changed the status strings to:

"submitted" - new request has been successfully submitted
"busy" - cluster is not accepting any new requests 'cause it is busy
"ready" - request has been processed and results are available

Helpful?

**Comment by jhammock** [comment]
sure, that works!
