### ISSUE TITLE
empty occurrence lists are not saved

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/freshdata#73]
Selectors that do not yield any results (empty occurrence lists) are not saved. Because the results (=no matches) are not saved, the system attempts to recalculate the results every time resources are available.

This explains why query mentioned in #72 switches back to "processing" after successfully completing the request.

**Comment by jhammock** [comment]
ah... I want to say this is an interesting quirk which should be left alone. Perhaps I will test GUODA with a different query...

**Comment by jhammock** [comment]
hmm... This query exhibits similar behavior. It seems very unlikely to be empty

http://api.effechecka.org/occurrences?limit=20&taxonSelector=Carnivora&traitSelector=&wktString=POLYGON%20%28%28-72.147216796875%2041.492120839687786%2C%20-72.147216796875%2043.11702412135048%2C%20-69.949951171875%2043.11702412135048%2C%20-69.949951171875%2041.492120839687786%2C%20-72.147216796875%2041.492120839687786%29%29

Immediately upon request in the widget it was processing
copying the parameters into the equivalent API query produced "Already reached maximum submission size"
upon which, refreshing the widget also produced "Already reached maximum submission size"

?

**Comment by jhammock** [comment]
nope, not empty. Returning this evidence to https://github.com/gimmefreshdata/freshdata/issues/72

**Comment by jhpoelen** [comment]
Now, empty collections are saved again. This regression was a left over from migration from cassandra to  hdfs.  

@jhammock Please confirm by closing this issue.

See attached screenshot for results related to http://gimmefreshdata.github.io/?limit=20&taxonSelector=Lepidopa&traitSelector=&wktString=POLYGON%20%28%28-72.147216796875%2041.492120839687786%2C%20-72.147216796875%2043.11702412135048%2C%20-69.949951171875%2043.11702412135048%2C%20-69.949951171875%2041.492120839687786%2C%20-72.147216796875%2041.492120839687786%29%29 

![screenshot from 2017-07-13 12-39-45](https://user-images.githubusercontent.com/1084872/28184557-aa82eb96-67c8-11e7-975e-233e7a6e03fb.png)
