### ISSUE TITLE
existing code

### ISSUE THREAD

**Issue by diatomsRcool** [gimmefreshdata/freshdata#77]
Where can I see the code that uses PySpark to make the checklists? I want to write my own code in the iDigBio jupyter notebook, but I don't seem to have access.

**Comment by jhpoelen** [comment]
I am not a python-ista (yet). Ideally you'd be able to reuse the idigbio-spark library - this way, you can re-use what is already there and make it better. @godfoder @mjcollin - is there a way to link idigbio-spark jar into the jupyter notebooks?

**Comment by diatomsRcool** [comment]
OK, I'm just looking for the code that generates the checklists. We saw 
it at TDWG.....

**Comment by jhpoelen** [comment]
The code used by effechecka.org is written in scala and available at https://github.com/bio-guoda/idigbio-spark . For instance, https://github.com/bio-guoda/idigbio-spark/blob/master/src/main/scala/ChecklistGenerator.scala . I am sure you can re-write in python and customize if desired.

**Comment by diatomsRcool** [comment]
OK, so ideally, what I would like to do is run the geo query in Pyspark, but there doesn't appear to be a library for that. That leaves three options: 1. I write a bunch of Pyspark code that does a geo query - nontrivial. 2. I learn scala - non trivial or 3. I put everything in a pandas data frame and use GeoPandas. I would prefer 3. Is there a reason we don't load data from parquet into a pandas data frame right away? Is it too much for pandas?

**Comment by jhpoelen** [comment]
(apologies for delayed reply) After a duckduckgo search on "python parquet library" I found https://stackoverflow.com/questions/33813815/how-to-read-a-parquet-file-into-pandas-dataframe . Please re-open this issue if that doesn't answer your question.
