### ISSUE TITLE
run update monitors using archive.guoda.bio

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/freshdata#78]
as discussed with @jhammock - "update monitors" has not yet completed after the move to the "big" cluster / hdfs .

**Comment by jhpoelen** [comment]
@jhammock made some progress on this, after some debugging, an update monitor job was started using jenkins. The job monitors the status of the submitted job and should complete whenever the update has completed in the cluster. See http://archive.guoda.bio/job/update%20monitors/98/console for current info. 

I'll check back later for completion.

**Comment by jhpoelen** [comment]
@godfoder @jhammock @diatomsRcool @mjcollin am running heavy job on cluster, please don't kill it unless you have something urgent to do. Included screenshot of driver info.

![screenshot from 2017-11-02 15-55-54](https://user-images.githubusercontent.com/1084872/32354308-65c12c18-bfe6-11e7-963d-2a36e4c958a7.png)

**Comment by diatomsRcool** [comment]
Please let us know when you are done

**Comment by jhpoelen** [comment]
Will do. You should also be able to see status at http://archive.guoda.bio/job/update%20monitors/ .

**Comment by jhpoelen** [comment]
Good news - first run has completed in 5h20m (see screenshot). 

Bad news - the run crashed due to GC error when writing the results to parquet files. (see attached stderr). Will have to try again after postmortem.

![screenshot from 2017-11-03 03-13-00](https://user-images.githubusercontent.com/1084872/32369472-7dab2288-c046-11e7-8542-79c5e95a72ba.png)

[stderr.log.txt](https://github.com/gimmefreshdata/freshdata/files/1440711/stderr.log.txt)

**Comment by jhpoelen** [comment]
@jhammock please note that due to failure, previous occurrence collections are unavailable. The monitors are available, and I am working on recalculating the collections from the datasets.

**Comment by jhpoelen** [comment]
@godfoder @jhammock @diatomsRcool @mjcollin am running another heavy job on cluster after first one failed (see above), please don't kill it unless you have something urgent to do. Included screenshot of driver info.

![screenshot from 2017-11-03 04-57-30](https://user-images.githubusercontent.com/1084872/32372777-8744fa28-c053-11e7-95b0-a8ea980664f9.png)

**Comment by jhpoelen** [comment]
status of the ```update monitor``` can be tracked http://archive.guoda.bio/job/update%20monitors/99 .

**Comment by jhpoelen** [comment]
http://archive.guoda.bio/job/update%20monitors/99 completed in 5h10m . . . with errors. This time, it appears that mesos09 lost connection with other executor nodes in cluster due to a timeout . 

The previously observed GC limit timeout error is no longer observed after changing the idigbio-spark library.

```
I1103 07:56:31.312685 19742 exec.cpp:161] Version: 1.0.0
I1103 07:56:31.314466 19748 exec.cpp:236] Executor registered on agent dabbc59d-84c3-4fb3-8baa-045c55e020fb-S4
17/11/03 07:56:36 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/11/03 07:56:45 WARN RetryInvocationHandler: A failover has occurred since the start of this method invocation attempt.
17/11/03 07:56:45 WARN RetryInvocationHandler: A failover has occurred since the start of this method invocation attempt.
17/11/03 07:56:45 WARN RetryInvocationHandler: A failover has occurred since the start of this method invocation attempt.
17/11/03 13:05:54 WARN NettyRpcEnv: Ignored failure: java.util.concurrent.TimeoutException: Cannot receive any reply in 10 seconds
```

errors on other executor nodes are - 

```
17/11/03 13:06:30 ERROR TransportResponseHandler: Still have 1 requests outstanding when connection from mesos09.acis.ufl.edu/10.13.44.39:36936 is closed
17/11/03 13:06:30 ERROR OneForOneBlockFetcher: Failed while starting block fetches
java.io.IOException: Connection from mesos09.acis.ufl.edu/10.13.44.39:36936 closed
	at org.apache.spark.network.client.TransportResponseHandler.channelInactive(TransportResponseHandler.java:128)
	at org.apache.spark.network.server.TransportChannelHandler.channelInactive(TransportChannelHandler.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:237)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:230)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:257)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:237)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:230)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:237)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:230)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
	at org.apache.spark.network.util.TransportFrameDecoder.channelInactive(TransportFrameDecoder.java:182)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:237)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:230)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1289)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:237)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:893)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:691)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:408)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:455)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
```

Attached the full log of the spark driver. 
[stderr-driver-update-monitors-20171103.txt](https://github.com/gimmefreshdata/freshdata/files/1441992/stderr-driver-update-monitors-20171103.txt)

**Comment by jhpoelen** [comment]
A third run http://archive.guoda.bio/view/Fresh%20Data%20jobs/job/update%20monitors/100 is attempting to be executed on the cluster. At time of writing, the request is queued due to lack of resources (many pyspark-shell frameworks running). This run contains only a single selector and uses /guoda/data/update-monitor-test/ as a staging area. This tests whether the number of selectors impact the performance and stability of the update.

**Comment by jhpoelen** [comment]
Run  http://archive.guoda.bio/view/Fresh%20Data%20jobs/job/update%20monitors/100 completed after waiting for about 3-4 hours for resources and completed in about 15-16 hours. Only a single executor was used and a single selector was successfully updated. Note that the previous runs used 86 selectors across 12 executors. So, the outcome of this third run is consistent with a hypothesis that the previous runs failed due to a scaling bug or resource tuning issue.  See attached log for details. 
[stderr-driver-update-monitor-test-20171104.readme.txt](https://github.com/gimmefreshdata/freshdata/files/1443520/stderr-driver-update-monitor-test-20171104.readme.txt)
[stderr-driver-update-monitor-test-20171104.txt](https://github.com/gimmefreshdata/freshdata/files/1443522/stderr-driver-update-monitor-test-20171104.txt)

A four runs has been started at http://archive.guoda.bio/job/update%20monitors/101/ . This run contains all 86 selectors/monitors and is currently waiting for resources to free up. The staging area /guoda/data/update-monitor-test-big/ is used.

**Comment by jhpoelen** [comment]
@godfoder @mjcollin http://archive.guoda.bio/job/update%20monitors/101/ has been queuing for over 24 hours now. It seems that many folks opened pyspark-shells 2 days ago (Friday) and I am not quite sure what the processes do other than reserve resources. 

I can see a bunch of solutions:

1. split cluster in two - a sandbox for experiments using shells and a production environment for running jobs. 
2. restrict access to notebooks
3. focus on running "trusted" jobs only and use other resources for educational purposes

![screenshot from 2017-11-05 07-55-23](https://user-images.githubusercontent.com/1084872/32416506-f39412b6-c1fe-11e7-84a2-791a062cfd30.png)

**Comment by godfoder** [comment]
We had a bunch of new users come in during a presentation. I've cleaned up idle notebooks and a number of occ2checklist jobs have started. I'll try and see if there is a good solution for this on the jupyter side of things before exploring those more drastic options.

**Comment by jhpoelen** [comment]
@godfoder - encouraging to hear that folks are getting familiar with jupyter notebooks and thanks for cleaning out the idle notebooks. 

I can confirm that http://archive.guoda.bio/job/update%20monitors/101 started about an hour ago (2017-11-06 0700 pacific) and has currently 3 active tasks with 41 cpus and 33 GB of memory using about 21% of the cluster resources. Hoping to report on outcomes later.

**Comment by jhpoelen** [comment]
http://archive.guoda.bio/job/update%20monitors/101 completed with errors after 7 hours of running. Prior to that the job had been queued and waiting for resources. It appears that the job started out with 3 tasks (~ 3 executors) increasing to 6 ~ 3 hours into the run, and finally ended with 13 tasks starting about 4 hours prior to completing. task 4 and 6 were killed and caused the entire job to fail. 

task 6 contained the following warning in the stderr : 

```
17/11/06 17:37:03 WARN TaskMemoryManager: Failed to allocate a page (67108864 bytes), try again.
... (23 identical warnings)
17/11/06 17:39:55 WARN TaskMemoryManager: Failed to allocate a page (67108864 bytes), try again.
```

task 4 seemed to have simply been asked to shutdown: 

```
I1106 17:40:05.010604 25711 exec.cpp:413] Executor asked to shutdown
```

and task 5 failed because it lost contact with executor 6 -
from task 5 /executor 5 stderr log - 
```
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
17/11/06 17:39:54 ERROR TransportResponseHandler: Still have 1 requests outstanding when connection from mesos06.acis.ufl.edu/10.13.44.30:33377 is closed
17/11/06 17:39:54 ERROR OneForOneBlockFetcher: Failed while starting block fetches
java.io.IOException: Connection from mesos06.acis.ufl.edu/10.13.44.30:33377 closed
	at org.apache.spark.network.client.TransportResponseHandler.channelInactive(TransportResponseHandler.java:128)
	at org.apache.spark.network.server.TransportChannelHandler.channelInactive(TransportChannelHandler.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:237)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:230)
```


According to the error log of the driver, the job was aborted, because executor 6 (task 6) was lost:

```
[Stage 7:>                                                        (0 + 10) / 10]17/11/06 17:39:54 WARN HeartbeatReceiver: Removing executor 6 with no recent heartbeats: 171509 ms exceeds timeout 120000 ms
17/11/06 17:39:54 ERROR TaskSchedulerImpl: Lost executor 6 on mesos06.acis.ufl.edu: Executor heartbeat timed out after 171509 ms
17/11/06 17:39:54 WARN TaskSetManager: Lost task 5.0 in stage 7.0 (TID 2378, mesos06.acis.ufl.edu, executor 6): ExecutorLostFailure (executor 6 exited caused by one of the running tasks) Reason: Executor heartbeat timed out after 171509 ms
17/11/06 17:39:54 ERROR TaskSetManager: Task 5 in stage 7.0 failed 1 times; aborting job
```

See attached error log for a full stderr here : 
[update-monitor-test-big-20171106-stderr.txt](https://github.com/gimmefreshdata/freshdata/files/1448615/update-monitor-test-big-20171106-stderr.txt)

and a screenshot of the task overview -

![screenshot from 2017-11-06 19-32-12](https://user-images.githubusercontent.com/1084872/32476228-d79a3ff4-c32a-11e7-9479-6108791c6725.png)

**Comment by jhpoelen** [comment]
Started http://archive.guoda.bio/view/Fresh%20Data%20jobs/job/update%20monitors/102/ with disable coalesce(10) in writing occurrence related parquets (see https://github.com/bio-guoda/idigbio-spark/commit/68612ce031462ef2a9c7b6b775421e3cc310c823). This would hopefully reduce the size of the partitions and avoid the (memory) page issue observed in the previous job.

**Comment by jhpoelen** [comment]
Looks like http://archive.guoda.bio/view/Fresh%20Data%20jobs/job/update%20monitors/102/ succeeded after I disabled the coalesce(10) writing the parquet files. The apparent successful run took about 15 hours and used 6 executors. In the three hours before completion, another 10 executors were added by mesos (see screenshot below).

@jhammock could you please poke around and see whether things in freshdata are working as expected? Note that I've added a lastModified in the monitor api results. This value indicates the last time a monitor was updated. Also note that the http://gimmefreshdata.github.io/monitors.html contains all monitor updates, so multiple entries for a single uuid can be expected. 

![screenshot from 2017-11-07 12-08-35](https://user-images.githubusercontent.com/1084872/32515358-b88d824e-c3b4-11e7-9e92-155aa9ff9c7d.png)

**Comment by jhammock** [comment]
Cool! Can confirm new records have appeared in existing monitors. Will poke around further.

**Comment by jhammock** [comment]
This updateMonitors job seems to have performed perfectly. Next question- can I kick off one just like it from Jupyter? Can learn new process steps if needed (and presumably this job should normally be run with some warning or at a pre-negotiated time.)

**Comment by jhpoelen** [comment]
Glad to hear things are in order. Closing issue. 

Will open separate issue on how to trigger an updateMonitors job.
