### ISSUE TITLE
non-research grade iNaturalist record found in Fresh Data

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/freshdata#8]
@yrhe please add info here so that we can investigate the iNat record.

**Comment by yrhe** [comment]
When I searched "Dermaptera" on Fresh Data, not all the iNat data under "occurrence id" were research grade. 

The screenshot for part of the searching result on Fresh Data:

<img width="1218" alt="screen shot 2016-03-23 at 10 26 25 pm" src="https://cloud.githubusercontent.com/assets/15819985/14006697/60394688-f146-11e5-97c6-f6a9e359073b.png">

For the first iNat data: http://www.inaturalist.org/observations/264943, it reaches "research" grade. 

The screenshot for this research grade data:
<img width="758" alt="screen shot 2016-03-23 at 10 29 39 pm" src="https://cloud.githubusercontent.com/assets/15819985/14006768/112bb6d8-f147-11e5-8826-78d8321c34b0.png">

But for the the second iNat data: http://www.inaturalist.org/observations/265402, it only reaches "needs id" grade. 

The screenshot for this needs id grade data:
<img width="748" alt="screen shot 2016-03-23 at 10 35 14 pm" src="https://cloud.githubusercontent.com/assets/15819985/14006857/cf185aa2-f147-11e5-87d0-f2a5ea42b7f7.png">

According to today's group meeting, we know that iNat data displayed on Fresh Data are from GBIF, not from EOL (please correct me if I remembered this wrong), and supposed to be research grade.

**Comment by jhpoelen** [comment]
thanks @yrhe !

**Comment by jhpoelen** [comment]
@kueda Yurong (@yrhe) found a non-research grade iNat observation http://www.inaturalist.org/observations/265402 in a 2015 copy of GBIF. Just curious - was this 2013 observation added to GBIF prior to the research-grade only rule or is there something else going on?

**Comment by kueda** [comment]
It may have been in GBIF because it was research-grade, or because of a bug on our end or theirs, but it doesn't seem to be there now. If it is please send me the URL and I'll investigate further.

**Comment by jhpoelen** [comment]
@kueda thanks for your prompt reply. 

I can confirm that iNaturalist observation  http://www.inaturalist.org/observations/265402 is no longer available through gbif (see http://www.gbif.org/occurrence/search?OCCURRENCE_ID=http%3A%2F%2Fwww.inaturalist.org%2Fobservations%2F265402), while observation http://www.inaturalist.org/observations/264943 is still available through gbif (see http://www.gbif.org/occurrence/search?OCCURRENCE_ID=http%3A%2F%2Fwww.inaturalist.org%2Fobservations%2F264943). 

Closing issue.

**Comment by yrhe** [comment]
@jhpoelen & @kueda Thank you both for helping solving this issue!
