### ISSUE TITLE
Busy status since last night

### ISSUE THREAD

**Issue by BugwoodCenter** [gimmefreshdata/freshdata#82]
I was trying to send a new request and have been getting 'Busy' since last night.  Is everything OK?

**Comment by jhammock** [comment]
I stopped a few old jobs on the cluster, hoping to un-logjam it. Try now?

**Comment by BugwoodCenter** [comment]
just tried and got busy

**Comment by jhpoelen** [comment]
A quick glance tells me that @mjcollin has started 2 jobs (4 and 6 days ago) that take up a little under 70% of cluster resources. So, yep, the cluster is busy. 

![screenshot from 2017-12-21 10-52-58](https://user-images.githubusercontent.com/1084872/34270472-2484c8fe-e63d-11e7-8988-13f24f244201.png)

**Comment by BugwoodCenter** [comment]
I'll hold out hope that @mjcollin sees this and has not left for vacation yet.  I'll try it intermittently rather than setting the server to poll continuously.

**Comment by jhpoelen** [comment]
@BugwoodCenter polling is pretty lightweight, no servers are harmed doing that.

**Comment by BugwoodCenter** [comment]
Hallelujah!  I have data!

**Comment by mjcollin** [comment]
Sorry about that, broke my own guidance of not using "large" notebooks during a hackathon last week. I've shut my notebooks down.
