### ISSUE TITLE
timeout on http://gimmefreshdata.github.io/monitors.html 

### ISSUE THREAD

**Issue by jhpoelen** [gimmefreshdata/freshdata#86]
When visiting http://gimmefreshdata.github.io/monitors.html no list of monitors is shown.

Expected: list containing 1675 monitors is shown. 

Actual: no monitors are shown.

Preliminary analysis shows that  1675 monitors have been created by the freshdata prototype.The initial prototype had far fewer monitors and allow for retrieve all monitors in one go. Following a switch from cassandra to hdfs to help facilitate maintenance ( #67 ) and the growth of the number of monitors, it appears some change is needed to made to serve the list of fresh data monitors through the api. 

Workaround: reduce number of (active) monitors.

**Comment by jhammock** [comment]
if manual curation of the monitors list is need, I can prune it if I've got access

**Comment by jhpoelen** [comment]
Here's how to count occurrence monitors:

```
$ hdfs dfs -ls /guoda/data/monitor/occurrence-summary/*/*/*/* | wc -l                                       
1677                   
```

If you'd like to manually curate the list, you can remove the snappy.parquet files by selecting the monitor uuids you don't need :
```
$ hdfs dfs -ls /guoda/data/monitor/occurrence-summary/*/*/*/* | head -n10                                   
Found 1 items                                                                                                                      
-rw-r--r--   3 hdfs supergroup       3618 2018-11-17 16:45 /guoda/data/monitor/occurrence-summary/u0=00/u1=44/u2=c3/uuid=0044c339-d
aa6-5527-a059-986a440ac183/part-01994-f1563191-247d-4ef8-b710-65419847c7ad.c000.snappy.parquet                                     
Found 1 items                                                                                                                      
-rw-r--r--   3 hdfs supergroup       1946 2019-03-04 09:51 /guoda/data/monitor/occurrence-summary/u0=00/u1=9e/u2=3f/uuid=009e3f8e-4
5cf-53ea-b264-ba050b4720e9/part-01804-782d1d67-d33d-4fcb-a8bf-6d4bd3c00566.c000.snappy.parquet                                     
Found 1 items                                                                                                                      
-rw-r--r--   3 hdfs supergroup       3615 2018-11-08 16:13 /guoda/data/monitor/occurrence-summary/u0=02/u1=3a/u2=c2/uuid=023ac275-3
33b-5fb7-940d-a3cea3a6e02f/part-01945-09027aae-37ef-44d6-8403-7691087fb6d4.c000.snappy.parquet                                     
Found 1 items                                                                                                                      
-rw-r--r--   3 hdfs supergroup       2040 2019-03-03 23:34 /guoda/data/monitor/occurrence-summary/u0=04/u1=5a/u2=1b/uuid=045a1b5a-1
795-58f7-88ab-cfe7096fbf8b/part-01680-b290dbf8-4fd9-4bd2-858d-716b2f6df9fc.c000.snappy.parquet                                     
Found 1 items                                                                                                                      
-rw-r--r--   3 hdfs supergroup       6314 2019-02-16 18:41 /guoda/data/monitor/occurrence-summary/u0=05/u1=0c/u2=96/uuid=050c964e-5
6a0-5050-a30a-54794548c1f2/part-01765-aa1a6c5c-2085-4dff-9fad-9c0e30801aac.c000.snappy.parquet
```

Alternatively, you can move rename the directory ```occurrence-summary``` to ```occurrence-summary-20190306``` and re-request your favorite monitors via gimmefreshdata.github.io to recreate the monitors from scratch.

Useful?

**Comment by jhpoelen** [comment]
Btw - the 18400 checklist monitors are managed separately. 

e.g.,

```
$ hdfs dfs -ls /guoda/data/monitor/checklist-summary/*/*/*/* | wc -l                                        
18400                  
```

**Comment by jhpoelen** [comment]
here's a reference to hdfs file management. https://hortonworks.com/tutorial/manage-files-on-hdfs-via-cli-ambari-files-view/section/1/ . Note the similarity with linux style file management (e.g., ```ls```, ```cp```, ```mkdir```).

**Comment by jhammock** [comment]
re-name and re-create sounds good. Do I need to do anything in hdfs to make the new 'occurrence-summary' or will that be generated when a new monitor is made?

**Comment by jhpoelen** [comment]
I'd create a new empty ```occurrence-summary``` directory after renaming the old one.

**Comment by jhammock** [comment]
OK, I have moved the old monitors, created a new occurrence-summary folder, and a new monitor has populated it. The only thing puzzling me now is that the new monitor is not behaving like a cached query. Perhaps I've forgotten how something works:

https://editors.eol.org/FreshData/monitors.php?uuid=aa045d13-bab9-5f34-9769-7548d142220f returns status=ready

but http://api.effechecka.org/occurrences?uuid=aa045d13-bab9-5f34-9769-7548d142220f 

has been thinking for a few minute without returning results. Same in the widget- status went from "busy" to "submitted" and then back to "busy"

**Comment by jhpoelen** [comment]
Glad to hear that the workaround is working as expected. 

On the behavior - when first creating a new monitor, the cluster is crunching a little to retrieve all the associated data. Submitted means that the crunch process was successfully started, "busy" means that the cluster is still working on a previous request. So, please try again in a little while and the results should appear as expected.

**Comment by jhpoelen** [comment]
btw - I am not sure what https://editors.eol.org/FreshData/monitors.php?uuid=aa045d13-bab9-5f34-9769-7548d142220f does. I believe this is a wrapper api made by one of your colleagues.

**Comment by jhammock** [comment]
yes, Eli made the monitor search API. I was expecting results mostly because the monitor had appeared in the folder in hdfs, but perhaps that doesn't mean it's populated yet. I'll report back later.

**Comment by jhpoelen** [comment]
looks like occurrence lists are getting generated (see attached image)
![screenshot from 2019-03-08 09-37-41](https://user-images.githubusercontent.com/1084872/54045228-e631f400-4185-11e9-8cff-f72abb54a302.png)

**Comment by jhpoelen** [comment]
And . . . it looks like HDFS is having issue, causing the api to misbehave and become unresponsive. 

```
19-03-08 12:24:14 WARN RetryInvocationHandler: Exception while invoking class org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo over mesos01.acis.ufl.edu/10.13.44.15:8020. Not retrying because failovers (15) exceeded maximum allowed (15)
java.net.ConnectException: Call From mesos06/10.13.44.30 to mesos01.acis.ufl.edu:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.GeneratedConstructorAccessor17.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:792)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:732)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	at org.apache.hadoop.ipc.Client.call(Client.java:1413)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
```
related to #85 .

**Comment by jhpoelen** [comment]
Silver lining is that our cluster is automatically restarting the api.effechecka.org service, so that whenever the HDFS issues go away, the api should start behaving normally again.

**Comment by jhammock** [comment]
The latest updateMonitors job completed normally
